import type { Conference } from '../types/game';

export const CONFERENCES: Conference[] = [
  { id: '3', name: 'Atlantic Coast', abbreviation: 'ACC' },
  { id: '2', name: 'American Athletic', abbreviation: 'AAC' },
  { id: '1', name: 'America East', abbreviation: 'AEC' },
  { id: '4', name: 'Atlantic Sun', abbreviation: 'ASUN' },
  { id: '8', name: 'Big 12', abbreviation: 'B12' },
  { id: '9', name: 'Big East', abbreviation: 'BE' },
  { id: '44', name: 'Big South-OVC', abbreviation: 'BSOV' },
  { id: '12', name: 'Big Ten', abbreviation: 'B1G' },
  { id: '46', name: 'Big West', abbreviation: 'BW' },
  { id: '15', name: 'Colonial Athletic', abbreviation: 'CAA' },
  { id: '16', name: 'Conference USA', abbreviation: 'CUSA' },
  { id: '43', name: 'Horizon League', abbreviation: 'HORZ' },
  { id: '18', name: 'Ivy League', abbreviation: 'IVY' },
  { id: '19', name: 'Metro Atlantic', abbreviation: 'MAAC' },
  { id: '20', name: 'Mid-American', abbreviation: 'MAC' },
  { id: '21', name: 'Mid-Eastern Athletic', abbreviation: 'MEAC' },
  { id: '22', name: 'Missouri Valley', abbreviation: 'MVC' },
  { id: '24', name: 'Mountain West', abbreviation: 'MWC' },
  { id: '25', name: 'Northeast', abbreviation: 'NEC' },
  { id: '26', name: 'Pac-12', abbreviation: 'P12' },
  { id: '27', name: 'Patriot League', abbreviation: 'PAT' },
  { id: '23', name: 'Southeastern', abbreviation: 'SEC' },
  { id: '28', name: 'Southern', abbreviation: 'SOCON' },
  { id: '29', name: 'Southland', abbreviation: 'SLC' },
  { id: '30', name: 'Southwestern Athletic', abbreviation: 'SWAC' },
  { id: '31', name: 'Sun Belt', abbreviation: 'SBC' },
  { id: '45', name: 'Summit League', abbreviation: 'SUMM' },
  { id: '33', name: 'West Coast', abbreviation: 'WCC' },
  { id: '34', name: 'Western Athletic', abbreviation: 'WAC' },
];
