export const FG_SCHOOLS: { id: number; abbr: string; name: string }[] = [
  { id: 1, abbr: 'ACU', name: 'Abilene Christian University' },
  { id: 7, abbr: 'AAMU', name: 'Alabama A&M University' },
  { id: 6, abbr: 'ALST', name: 'Alabama State University' },
  { id: 9, abbr: 'ALCN', name: 'Alcorn State University' },
  { id: 10, abbr: 'APP', name: 'Appalachian State University' },
  { id: 11, abbr: 'ASU', name: 'Arizona State University' },
  { id: 14, abbr: 'ARST', name: 'Arkansas State University' },
  { id: 18, abbr: 'AUB', name: 'Auburn University' },
  { id: 19, abbr: 'APSU', name: 'Austin Peay State University' },
  { id: 20, abbr: 'BALL', name: 'Ball State University' },
  { id: 21, abbr: 'BAY', name: 'Baylor University' },
  { id: 23, abbr: 'BELL', name: 'Bellarmine University' },
  { id: 22, abbr: 'BEL', name: 'Belmont University' },
  { id: 24, abbr: 'BCU', name: 'Bethune Cookman University' },
  { id: 26, abbr: 'BC', name: 'Boston College' },
  { id: 27, abbr: 'BGSU', name: 'Bowling Green State University' },
  { id: 28, abbr: 'BRAD', name: 'Bradley University' },
  { id: 29, abbr: 'BYU', name: 'Brigham Young University' },
  { id: 31, abbr: 'BRY', name: 'Bryant University' },
  { id: 32, abbr: 'BUCK', name: 'Bucknell University' },
  { id: 33, abbr: 'BUT', name: 'Butler University' },
  { id: 39, abbr: 'CBU', name: 'California Babtist University' },
  { id: 34, abbr: 'CP', name: 'California Polytechnic State University' },
  { id: 40, abbr: 'CSUB', name: 'California State University Bakersfield' },
  { id: 81, abbr: 'FRES', name: 'California State University Fresno' },
  { id: 35, abbr: 'CSUF', name: 'California State University Fullerton' },
  { id: 36, abbr: 'CSUN', name: 'California State University Northridge' },
  { id: 38, abbr: 'SAC', name: 'California State University Sacramento' },
  { id: 41, abbr: 'CAM', name: 'Campbell University' },
  { id: 42, abbr: 'CAN', name: 'Canisius College' },
  { id: 44, abbr: 'CMU', name: 'Central Michigan University' },
  { id: 47, abbr: 'CHSO', name: 'Charleston Southern University' },
  { id: 49, abbr: 'CLEM', name: 'Clemson University' },
  { id: 50, abbr: 'CCU', name: 'Coastal Carolina University' },
  { id: 51, abbr: 'COFC', name: 'College of Charleston (South Carolina)' },
  { id: 300, abbr: 'W&M', name: 'College of William and Mary' },
  { id: 97, abbr: 'HC', name: 'College of the Holy Cross' },
  { id: 56, abbr: 'CREI', name: 'Creighton University' },
  { id: 57, abbr: 'DBU', name: 'Dallas Baptist University' },
  { id: 59, abbr: 'DAV', name: 'Davidson College' },
  { id: 62, abbr: 'DSU', name: 'Delaware State University' },
  { id: 63, abbr: 'UTU', name: 'Dixie State College of Utah' },
  { id: 64, abbr: 'DUKE', name: 'Duke University' },
  { id: 65, abbr: 'ECU', name: 'East Carolina University' },
  { id: 67, abbr: 'ETSU', name: 'East Tennessee State University' },
  { id: 69, abbr: 'EIU', name: 'Eastern Illinois University' },
  { id: 68, abbr: 'EKU', name: 'Eastern Kentucky University' },
  { id: 66, abbr: 'EMU', name: 'Eastern Michigan University' },
  { id: 70, abbr: 'ELON', name: 'Elon University' },
  { id: 72, abbr: 'FAIR', name: 'Fairfield University' },
  { id: 77, abbr: 'FAMU', name: 'Florida A&M University' },
  { id: 75, abbr: 'FAU', name: 'Florida Atlantic University' },
  { id: 79, abbr: 'FGCU', name: 'Florida Gulf Coast University' },
  { id: 76, abbr: 'FIU', name: 'Florida International University' },
  { id: 78, abbr: 'FSU', name: 'Florida State University' },
  { id: 80, abbr: 'FOR', name: 'Fordham University' },
  { id: 82, abbr: 'GWEB', name: 'Gardner-Webb University' },
  { id: 83, abbr: 'GMU', name: 'George Mason University' },
  { id: 84, abbr: 'GW', name: 'George Washington University' },
  { id: 85, abbr: 'GTWN', name: 'Georgetown University' },
  { id: 88, abbr: 'GT', name: 'Georgia Institute of Technology' },
  { id: 87, abbr: 'GASO', name: 'Georgia Southern University' },
  { id: 89, abbr: 'GAST', name: 'Georgia State University' },
  { id: 90, abbr: 'GONZ', name: 'Gonzaga University' },
  { id: 91, abbr: 'GRAM', name: 'Grambling State University' },
  { id: 92, abbr: 'GCU', name: 'Grand Canyon University' },
  { id: 95, abbr: 'HPU', name: 'High Point University' },
  { id: 96, abbr: 'HOF', name: 'Hofstra University' },
  { id: 99, abbr: 'HCU', name: 'Houston Christian University' },
  { id: 101, abbr: 'ILST', name: 'Illinois State University' },
  { id: 105, abbr: 'INST', name: 'Indiana State University' },
  { id: 104, abbr: 'IU', name: 'Indiana University Bloomington' },
  { id: 106, abbr: 'IONA', name: 'Iona College' },
  { id: 111, abbr: 'JKST', name: 'Jackson State University' },
  { id: 110, abbr: 'JVST', name: 'Jacksonville State University' },
  { id: 109, abbr: 'JAX', name: 'Jacksonville University' },
  { id: 112, abbr: 'JMU', name: 'James Madison University' },
  { id: 114, abbr: 'KSU', name: 'Kansas State University' },
  { id: 115, abbr: 'KENN', name: 'Kennesaw State University' },
  { id: 116, abbr: 'KENT', name: 'Kent State University' },
  { id: 309, abbr: 'LAS', name: 'La Salle University' },
  { id: 119, abbr: 'LAM', name: 'Lamar University' },
  { id: 120, abbr: 'LEM', name: 'Le Moyne College' },
  { id: 121, abbr: 'LEH', name: 'Lehigh University' },
  { id: 122, abbr: 'LIB', name: 'Liberty University' },
  { id: 123, abbr: 'LIN', name: 'Lindenwood University' },
  { id: 124, abbr: 'LIP', name: 'Lipscomb University' },
  { id: 125, abbr: 'LBSU', name: 'Long Beach State University' },
  { id: 127, abbr: 'LIU', name: 'Long Island University Brooklyn Campus' },
  { id: 126, abbr: 'LONG', name: 'Longwood University' },
  { id: 130, abbr: 'LSU', name: 'Louisiana State University' },
  { id: 132, abbr: 'LT', name: 'Louisiana Tech University' },
  { id: 133, abbr: 'LMU', name: 'Loyola Marymount University' },
  { id: 135, abbr: 'MAN', name: 'Manhattan College' },
  { id: 139, abbr: 'MRST', name: 'Marist College' },
  { id: 140, abbr: 'MRSH', name: 'Marshall University' },
  { id: 143, abbr: 'MCN', name: 'McNeese State University' },
  { id: 145, abbr: 'MER', name: 'Mercer University' },
  { id: 311, abbr: 'MERC', name: 'Mercyhurst College' },
  { id: 149, abbr: 'M-OH', name: 'Miami University (Ohio)' },
  { id: 151, abbr: 'MSU', name: 'Michigan State University' },
  { id: 152, abbr: 'MTSU', name: 'Middle Tennessee State University' },
  { id: 155, abbr: 'MSST', name: 'Mississippi State University' },
  { id: 156, abbr: 'MVSU', name: 'Mississippi Valley State University' },
  { id: 158, abbr: 'MOST', name: 'Missouri State University' },
  { id: 159, abbr: 'MONM', name: 'Monmouth University' },
  { id: 160, abbr: 'MORE', name: 'Morehead State University' },
  { id: 161, abbr: 'MSM', name: 'Mount St. Mary\'s University' },
  { id: 162, abbr: 'MUR', name: 'Murray State University' },
  { id: 171, abbr: 'NJIT', name: 'New Jersey Institute of Technology' },
  { id: 169, abbr: 'NMSU', name: 'New Mexico State University' },
  { id: 172, abbr: 'NIA', name: 'Niagara University' },
  { id: 173, abbr: 'NICH', name: 'Nicholls State University' },
  { id: 174, abbr: 'NORF', name: 'Norfolk State University' },
  { id: 188, abbr: 'NCAT', name: 'North Carolina A&T State University' },
  { id: 176, abbr: 'NCSU', name: 'North Carolina State University' },
  { id: 179, abbr: 'NDSU', name: 'North Dakota State University' },
  { id: 181, abbr: 'NE', name: 'Northeastern University' },
  { id: 183, abbr: 'NIU', name: 'Northern Illinois University' },
  { id: 189, abbr: 'NKU', name: 'Northern Kentucky University' },
  { id: 185, abbr: 'NWST', name: 'Northwestern State University' },
  { id: 184, abbr: 'NU', name: 'Northwestern University' },
  { id: 192, abbr: 'OAK', name: 'Oakland University' },
  { id: 194, abbr: 'OSU', name: 'Ohio State University' },
  { id: 193, abbr: 'OHIO', name: 'Ohio University' },
  { id: 196, abbr: 'OKST', name: 'Oklahoma State University' },
  { id: 197, abbr: 'ODU', name: 'Old Dominion University' },
  { id: 198, abbr: 'ORU', name: 'Oral Roberts University' },
  { id: 199, abbr: 'ORST', name: 'Oregon State University' },
  { id: 203, abbr: 'PSU', name: 'Pennsylvania State University' },
  { id: 204, abbr: 'PEPP', name: 'Pepperdine University' },
  { id: 207, abbr: 'PV', name: 'Prairie View A&M University' },
  { id: 208, abbr: 'PRES', name: 'Presbyterian College' },
  { id: 210, abbr: 'PUR', name: 'Purdue University' },
  { id: 211, abbr: 'QUC', name: 'Queens University of Charlotte' },
  { id: 212, abbr: 'QUIN', name: 'Quinnipiac University' },
  { id: 213, abbr: 'RAD', name: 'Radford University' },
  { id: 215, abbr: 'RICE', name: 'Rice University' },
  { id: 218, abbr: 'RUTG', name: 'Rutgers State Univ of New Jersey New Brunswick' },
  { id: 219, abbr: 'SHU', name: 'Sacred Heart University' },
  { id: 244, abbr: 'JOES', name: 'Saint Joseph\'s University' },
  { id: 245, abbr: 'SLU', name: 'Saint Louis University' },
  { id: 220, abbr: 'SHSU', name: 'Sam Houston State University' },
  { id: 221, abbr: 'SAM', name: 'Samford University' },
  { id: 222, abbr: 'SDSU', name: 'San Diego State University' },
  { id: 224, abbr: 'SJSU', name: 'San Jose State University' },
  { id: 226, abbr: 'SCU', name: 'Santa Clara University' },
  { id: 227, abbr: 'SEA', name: 'Seattle University' },
  { id: 228, abbr: 'HALL', name: 'Seton Hall University' },
  { id: 232, abbr: 'SDST', name: 'South Dakota State University' },
  { id: 234, abbr: 'SEMO', name: 'Southeast Missouri State University' },
  { id: 238, abbr: 'SELA', name: 'Southeastern Louisiana University' },
  { id: 241, abbr: 'SIUE', name: 'Southern Illinois University Edwardsville' },
  { id: 235, abbr: 'SIU', name: 'Southern Illinois University at Carbondale' },
  { id: 239, abbr: 'SOU', name: 'Southern University Baton Rouge' },
  { id: 243, abbr: 'SBU', name: 'St. Bonaventure University' },
  { id: 247, abbr: 'SJU', name: 'St. John\'s University (New York)' },
  { id: 246, abbr: 'SMC', name: 'St. Mary\'s College of California' },
  { id: 250, abbr: 'STAN', name: 'Stanford University' },
  { id: 25, abbr: 'BING', name: 'State University of New York at Binghamton' },
  { id: 252, abbr: 'SFA', name: 'Stephen F. Austin State University' },
  { id: 251, abbr: 'STET', name: 'Stetson University' },
  { id: 254, abbr: 'STO', name: 'Stonehill College' },
  { id: 253, abbr: 'STBK', name: 'Stony Brook University' },
  { id: 255, abbr: 'TAR', name: 'Tarleton State University' },
  { id: 257, abbr: 'TNTC', name: 'Tennessee Technological University' },
  { id: 263, abbr: 'TA&M', name: 'Texas A&M University College Station' },
  { id: 266, abbr: 'AMCC', name: 'Texas A&M University Corpus Christi' },
  { id: 259, abbr: 'TCU', name: 'Texas Christian University' },
  { id: 267, abbr: 'TXSO', name: 'Texas Southern University' },
  { id: 264, abbr: 'TXST', name: 'Texas State University San Marcos' },
  { id: 260, abbr: 'TTU', name: 'Texas Tech University' },
  { id: 269, abbr: 'CIT', name: 'The Citadel' },
  { id: 271, abbr: 'TOW', name: 'Towson University' },
  { id: 272, abbr: 'TROY', name: 'Troy University' },
  { id: 273, abbr: 'TULN', name: 'Tulane University' },
  { id: 2, abbr: 'AFA', name: 'U.S. Air Force Academy' },
  { id: 17, abbr: 'ARMY', name: 'U.S. Military Academy' },
  { id: 163, abbr: 'NAVY', name: 'U.S. Naval Academy' },
  { id: 3, abbr: 'AKR', name: 'University of Akron' },
  { id: 4, abbr: 'ALA', name: 'University of Alabama Tuscaloosa' },
  { id: 5, abbr: 'UAB', name: 'University of Alabama at Birmingham' },
  { id: 12, abbr: 'ARIZ', name: 'University of Arizona' },
  { id: 13, abbr: 'ARK', name: 'University of Arkansas Fayetteville' },
  { id: 15, abbr: 'LR', name: 'University of Arkansas Little Rock' },
  { id: 16, abbr: 'UAPB', name: 'University of Arkansas Pine Bluff' },
  { id: 37, abbr: 'CAL', name: 'University of California Berkeley' },
  { id: 277, abbr: 'UCD', name: 'University of California Davis' },
  { id: 274, abbr: 'UCI', name: 'University of California Irvine' },
  { id: 279, abbr: 'UCLA', name: 'University of California Los Angeles' },
  { id: 276, abbr: 'UCR', name: 'University of California Riverside' },
  { id: 278, abbr: 'UCSD', name: 'University of California San Diego' },
  { id: 275, abbr: 'UCSB', name: 'University of California Santa Barbara' },
  { id: 46, abbr: 'CARK', name: 'University of Central Arkansas' },
  { id: 43, abbr: 'UCF', name: 'University of Central Florida' },
  { id: 48, abbr: 'CIN', name: 'University of Cincinnati' },
  { id: 53, abbr: 'CONN', name: 'University of Connecticut' },
  { id: 60, abbr: 'DAY', name: 'University of Dayton' },
  { id: 61, abbr: 'DEL', name: 'University of Delaware' },
  { id: 71, abbr: 'EVAN', name: 'University of Evansville' },
  { id: 74, abbr: 'FLA', name: 'University of Florida' },
  { id: 86, abbr: 'UGA', name: 'University of Georgia' },
  { id: 94, abbr: 'HAW', name: 'University of Hawaii Manoa' },
  { id: 98, abbr: 'HOU', name: 'University of Houston' },
  { id: 100, abbr: 'ILL', name: 'University of Illinois Urbana-Champaign' },
  { id: 102, abbr: 'UIC', name: 'University of Illinois at Chicago' },
  { id: 107, abbr: 'IOWA', name: 'University of Iowa' },
  { id: 113, abbr: 'KU', name: 'University of Kansas' },
  { id: 117, abbr: 'UK', name: 'University of Kentucky' },
  { id: 131, abbr: 'UL', name: 'University of Louisiana at Lafayette' },
  { id: 128, abbr: 'ULM', name: 'University of Louisiana at Monroe' },
  { id: 129, abbr: 'LOU', name: 'University of Louisville' },
  { id: 134, abbr: 'ME', name: 'University of Maine Orono' },
  { id: 136, abbr: 'MD', name: 'University of Maryland College Park' },
  { id: 138, abbr: 'UMES', name: 'University of Maryland Eastern Shore' },
  { id: 142, abbr: 'UML', name: 'University of Massachusetts at Lowell' },
  { id: 144, abbr: 'MEM', name: 'University of Memphis' },
  { id: 148, abbr: 'MIA', name: 'University of Miami (Florida)' },
  { id: 150, abbr: 'MICH', name: 'University of Michigan' },
  { id: 153, abbr: 'MINN', name: 'University of Minnesota Twin Cities' },
  { id: 154, abbr: 'MISS', name: 'University of Mississippi' },
  { id: 157, abbr: 'MIZ', name: 'University of Missouri Columbia' },
  { id: 164, abbr: 'NEB', name: 'University of Nebraska Lincoln' },
  { id: 165, abbr: 'OMA', name: 'University of Nebraska at Omaha' },
  { id: 166, abbr: 'NEV', name: 'University of Nevada' },
  { id: 167, abbr: 'UNLV', name: 'University of Nevada Las Vegas' },
  { id: 168, abbr: 'UNM', name: 'University of New Mexico' },
  { id: 170, abbr: 'UNO', name: 'University of New Orleans' },
  { id: 190, abbr: 'UNA', name: 'University of North Alabama' },
  { id: 177, abbr: 'UNCA', name: 'University of North Carolina Asheville' },
  { id: 175, abbr: 'UNC', name: 'University of North Carolina Chapel Hill' },
  { id: 186, abbr: 'CLT', name: 'University of North Carolina Charlotte' },
  { id: 187, abbr: 'UNCW', name: 'University of North Carolina Wilmington' },
  { id: 178, abbr: 'UNCG', name: 'University of North Carolina at Greensboro' },
  { id: 180, abbr: 'UNF', name: 'University of North Florida' },
  { id: 182, abbr: 'UNCO', name: 'University of Northern Colorado' },
  { id: 191, abbr: 'ND', name: 'University of Notre Dame' },
  { id: 195, abbr: 'OU', name: 'University of Oklahoma' },
  { id: 200, abbr: 'ORE', name: 'University of Oregon' },
  { id: 205, abbr: 'PITT', name: 'University of Pittsburgh' },
  { id: 206, abbr: 'PORT', name: 'University of Portland' },
  { id: 214, abbr: 'URI', name: 'University of Rhode Island' },
  { id: 216, abbr: 'RICH', name: 'University of Richmond' },
  { id: 225, abbr: 'USD', name: 'University of San Diego' },
  { id: 223, abbr: 'SF', name: 'University of San Francisco' },
  { id: 230, abbr: 'USA', name: 'University of South Alabama' },
  { id: 231, abbr: 'SC', name: 'University of South Carolina Columbia' },
  { id: 242, abbr: 'UPST', name: 'University of South Carolina Upstate' },
  { id: 233, abbr: 'USF', name: 'University of South Florida' },
  { id: 237, abbr: 'USC', name: 'University of Southern California' },
  { id: 240, abbr: 'USI', name: 'University of Southern Indiana' },
  { id: 236, abbr: 'USM', name: 'University of Southern Mississippi' },
  { id: 256, abbr: 'TENN', name: 'University of Tennessee Knoxville' },
  { id: 258, abbr: 'UTM', name: 'University of Tennessee at Martin' },
  { id: 268, abbr: 'RGV', name: 'University of Texas Rio Grande Valley' },
  { id: 261, abbr: 'UTA', name: 'University of Texas at Arlington' },
  { id: 265, abbr: 'TEX', name: 'University of Texas at Austin' },
  { id: 262, abbr: 'UTSA', name: 'University of Texas at San Antonio' },
  { id: 270, abbr: 'TOL', name: 'University of Toledo' },
  { id: 280, abbr: 'UTAH', name: 'University of Utah' },
  { id: 285, abbr: 'UVA', name: 'University of Virginia' },
  { id: 291, abbr: 'WASH', name: 'University of Washington' },
  { id: 312, abbr: 'WES', name: 'University of West Georgia' },
  { id: 302, abbr: 'MILW', name: 'University of Wisconsin Milwaukee' },
  { id: 103, abbr: 'UIW', name: 'University of the Incarnate Word' },
  { id: 201, abbr: 'PAC', name: 'University of the Pacific' },
  { id: 281, abbr: 'UVU', name: 'Utah Valley State College' },
  { id: 282, abbr: 'VAL', name: 'Valparaiso University' },
  { id: 283, abbr: 'VAN', name: 'Vanderbilt University' },
  { id: 284, abbr: 'VILL', name: 'Villanova University' },
  { id: 286, abbr: 'VCU', name: 'Virginia Commonwealth University' },
  { id: 287, abbr: 'VMI', name: 'Virginia Military Institute' },
  { id: 288, abbr: 'VT', name: 'Virginia Polytechnic Institute & State University' },
  { id: 289, abbr: 'WAG', name: 'Wagner College' },
  { id: 290, abbr: 'WAKE', name: 'Wake Forest University' },
  { id: 292, abbr: 'WSU', name: 'Washington State University' },
  { id: 296, abbr: 'WVU', name: 'West Virginia University' },
  { id: 297, abbr: 'WCU', name: 'Western Carolina University' },
  { id: 293, abbr: 'WIU', name: 'Western Illinois University' },
  { id: 294, abbr: 'WKU', name: 'Western Kentucky University' },
  { id: 295, abbr: 'WMU', name: 'Western Michigan University' },
  { id: 299, abbr: 'WICH', name: 'Wichita State University' },
  { id: 301, abbr: 'WIN', name: 'Winthrop University' },
  { id: 303, abbr: 'WOF', name: 'Wofford College' },
  { id: 304, abbr: 'WRST', name: 'Wright State University' },
  { id: 305, abbr: 'XAV', name: 'Xavier University' },
  { id: 307, abbr: 'YSU', name: 'Youngstown State University' },
];
// 287 schools, generated from FanGraphs 2026 season data
